### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by msimerson** [tugrul/node-dnszone#1]
This project appears to have fallen into abandonment. Is there any chance you'd consider [un-publishing](https://docs.npmjs.com/cli/v8/commands/npm-unpublish/) it from NPM?  I would like to use a similar name space "dns-zone" for a package but cannot because it's too similar to this one:

````
➜  dns-zone ✗ npm publish
npm notice 
npm notice 📦  dns-zone@0.1.0
<snip>
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/dns-zone - Package name too similar to existing package dnszone; try renaming your package to '@tnpi/dns-zone' and publishing with 'npm publish --access=public' instead
````

Thanks for considering this.

**Comment by msimerson** [comment]
Hello?

**Comment by tugrul** [comment]
Hi @msimerson,

This project is looking like abandoned but it is not. Some internal projects are using this package and name changing can cause side effects.

You may consider append namespace like `@msimerson/dns-zone`

Regards,
Tuğrul

**Comment by msimerson** [comment]
> This project is looking like abandoned but it is not.

Fair enough. If that ever changes, please consider [deprecating](https://docs.npmjs.com/cli/v8/commands/npm-deprecate) the package on npm. Thanks, and have a nice day.
